service:
  golangci-lint-version: 1.38.x

run:
  tests: false
  modules-download-mode: readonly

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  funlen:
    lines: 100
    statements: 75
  gofumpt:
    extra-rules: true
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  misspell:
    locale: US
  nolintlint:
    allow-unused: false
    allow-leading-space: true
  gci:
    local-prefixes: github.com/trustwallet
  unparam:
    check-exported: true
  unused:
    check-exported: true
  errorlint:
    errorf: true
  gocyclo:
    min-complexity: 25
  wrapcheck:
    ignorePackageGlobs:
      - github.com/trustwallet/*
issues:
  new: false
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    - asciicheck
    - bodyclose
    - dogsled
    - dupl
    - durationcheck
    - errorlint
    - exhaustive
    - exportloopref
    - forcetypeassert
    - funlen
    - gci
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    # - goerr113
    - gofmt
    - gofumpt
    - goimports
    # - gomnd
    - goprintffuncname
    - gosec
    - importas
    - lll
    - makezero
    - misspell
    - nakedret
    - nestif
    - nilerr
    - nlreturn
    - nolintlint
    - paralleltest
    - prealloc
    - predeclared
    - revive
    - rowserrcheck
    - sqlclosecheck
    - stylecheck
    - testpackage
    - thelper
    - tparallel
    - unconvert
    - unparam
    - wastedassign
    - whitespace
    # - wrapcheck