version: "3.9"

services:
  api:
    depends_on:
      - postgres
    build:
      context: .
      dockerfile: cmd/api/Dockerfile
    volumes:
      - .env:/.env
    ports:
      - 2010:2010
    networks:
      - default

  postgres:
    image: postgres:9.6
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=assets
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:

volumes:
  postgres:
    external: true
