app:
  log_level: info

client_urls:
  binancedex: "https://dex-atlantic.binance.org"

validators_settings:
  image_file:
    size_kb: 100
    max_w: 512
    max_h: 512
    min_w: 50
    min_h: 50

  root_folder:
    allowed_files:
      - ".github"
      - "blockchains"
      - "dapps"
      - "media"
      - "node_modules"
      - "script-old"
      - "script"
      - "test"
      - ".gitignore"
      - "azure-pipelines.yml"
      - "jest.config.js"
      - "LICENSE"
      - "package-lock.json"
      - "package.json"
      - "README.md"
      - ".git"
      - ".eslintignore"
      - ".eslintrc.js"
      - "cmd"
      - "go.mod"
      - "go.sum"
    skip_files:
      - "node_modules"

  chain_folder:
    allowed_files:
      - "assets"
      - "tokenlist.json"
      - "validators"
      - "info"

  asset_folder:
    allowed_files:
      - "logo.png"
      - "info.json"

  chain_info_folder:
    has_files:
      - "logo.png"
      - "info.json"

  chain_validators_asset_folder:
    has_files:
      - "logo.png"

  dapps_folder:
    ext: ".png"

  coin_info_file:
    tags:
      - id: stablecoin
        name: Stablecoin
        description: Tokens that are fixed to an external asset, e.g. the US dollar.
      - id: wrapped
        name: Wrapped
        description: Tokens that are wrapped or peg representation of digital assets. Excluded
          stablecoins
      - id: synthetics
        name: Synthetics
        description: Synthetic assets created to track the value of another asset
      - id: nft
        name: NFT
        description: Non-fungible tokens or tokens associated with the NFT ecosystem.
      - id: governance
        name: Governance
        description: Tokens that used to participate in the governance process of the project.
      - id: defi
        name: DeFi
        description: Tokens that are used for variety of decentralized financial applications.
      - id: staking
        name: Staking
        description: Tokens that are used for staking to receive rewards.
      - id: staking-native
        name: Staking Native
        description: Coins/Blockchains that are used for staking to secure the network to
          receive rewards.
      - id: privacy
        name: Privacy
        description: Privacy tokens.
      - id: nsfw
        name: NSFW
        description: Content Not suitable for work.
